spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_crm
    username: root
    password: 2004

#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Use this for MySQL
        # dialect: org.hibernate.dialect.MariaDBDialect # Uncomment this for MariaDB

  # Uncomment the below section if you want to use HikariCP as the connection pool
  # hikari:
  #   pool-name: HikariPool-1
  #   minimum-idle: 5
  #   maximum-pool-size: 10
  #   idle-timeout: 30000
  #   max-lifetime: 1800000
  #   connection-timeout: 30000

# Additional Hibernate settings if needed
# logging:
#   level:
#     org:
#       hibernate: DEBUG
